#$(warning KERNELRELEASE=$(KERNELRELEASE))

EXTRA_CFLAGS = -g -O0
EXTRA_CFLAGS += -DVAR1=95
EXTRA_CFLAGS += -DVAR2=121

ifeq ($(KERNELRELEASE),)

PWD := $(shell pwd)
KERNEL_SRC := /lib/modules/$(shell uname -r)/build

modules:
	$(MAKE) $@ \
		-C $(KERNEL_SRC) \
		M=$(PWD)

modules_install: modules
	$(MAKE) $@ \
		-C $(KERNEL_SRC) \
		M=$(PWD)

clean:
	$(MAKE) $@ \
		-C $(KERNEL_SRC) \
		M=$(PWD)

.PHONY: modules modules_install clean

else

obj-m := hello.o

endif
